apiVersion: v1
kind: Service
metadata:
  name: gitdash
  namespace: gitdash
  labels:
    app.kubernetes.io/name: gitdash
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gitdash
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
