apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitdash.configmapName" . }}
  namespace: {{ include "gitdash.namespace" . }}
  labels:
    {{- include "gitdash.labels" . | nindent 4 }}
data:
  MODE: {{ .Values.config.mode | quote }}
  NEXT_PUBLIC_APP_URL: {{ .Values.config.appUrl | quote }}
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
